yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'
urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Наименование группы', max_length=200)
    slug = models.SlugField('Уникальный адрес группы', unique=True)
    description = models.TextField(
        'Описание группы',
    )

    def __str__(self) -> str:
        return str(self.title)

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )

    group = models.ForeignKey(
        Group,
        models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Загрузите картинку',
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return f'{self.text[:settings.MAX_POST_STR]}'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        'Текст комментария', help_text='Введите текст комментария'
    )
    created = models.DateTimeField('Дата публикации', auto_now_add=True)

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self) -> str:
        return f'{self.text[:settings.MAX_POST_STR]}'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                name='user_author_pair_unique',
                fields=['user', 'author'],
            ),
        ]
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self) -> str:
        return f'{self.author}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def my_paginator(request, list_name, num_on_page):
    paginator = Paginator(list_name, num_on_page)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@cache_page(20, key_prefix='index_page')
def index(request):
    """Function index make selection of 10 posts,
    create content and return home page (index.html) with context
    """
    post_list = Post.objects.select_related("author", "group")
    context = {
        'page_obj': my_paginator(request, post_list, settings.POSTS_PER_PAGE),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """
    Function group_posts collect content and create page (group_list.html)
    where display posts in group <slug>. Else, return 404 page.
    """
    group_post = get_object_or_404(Group, slug=slug)
    posts = group_post.posts.select_related('author', 'group')
    context = {
        'group': group_post,
        'page_obj': my_paginator(request, posts, settings.POSTS_PER_GROUP),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Function profile collect content and create page (profile.html)
    where display posts by author <username>. Else, return 404 page.
    """
    auth = get_object_or_404(User, username=username)
    auth_post_list = auth.posts.select_related('author', 'group')
    is_following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=auth).exists()
    )
    context = {
        'page_obj': my_paginator(
            request, auth_post_list, settings.POSTS_PER_PAGE
        ),
        'author': auth,
        'following': is_following,
        'user': request.user,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """
    Function post_detail collect content and create
    page (post_detail.html) where display detail
    information of post with num of post_id.
    """
    post_id_detail = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments_list = post_id_detail.comments.all()
    context = {
        'post': post_id_detail,
        'form': form,
        'comments': comments_list,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """
    Function create new post. It's available only
    for autenficated users.
    """
    form = PostForm(request.POST or None, files=request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """
    Function edit post. It's available only
    for author of post.
    """
    unique_post = get_object_or_404(Post, pk=post_id)
    if unique_post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=unique_post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post': unique_post,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    """
    Function create new comment for post.
    It's available only for autenficated users.
    """
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Function displays the posts of authors
    to which the current user is subscribed."""
    post_list = Post.objects.filter(author__following__user=request.user)
    context = {
        'page_obj': my_paginator(request, post_list, settings.POSTS_PER_PAGE),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Function help to subscribe the user to author."""
    auth = get_object_or_404(User, username=username)
    if (
        not (Follow.objects.filter(user=request.user, author=auth).exists())
        and auth != request.user
    ):
        Follow.objects.create(user=request.user, author=auth)
    return redirect('posts:profile', auth)


@login_required
def profile_unfollow(request, username):
    """Function help to unsubscribe the user to author."""
    author = get_object_or_404(User, username=username)
    if Follow.objects.filter(user=request.user, author=author).exists():
        Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">
          {% include 'posts/includes/check_errors.html' %}
          {% if is_edit %}
            <form method="post"
              action= "{% url 'posts:post_edit' post.pk %}"
              enctype="multipart/form-data">
          {% else %}
            <form method="post"
              action = "{% url 'posts:post_create' %}"
              enctype="multipart/form-data">
          {% endif %}
          {% csrf_token %}
          {% for field in form %}
            {% include 'posts/includes/form_fields.html' %}
          {% endfor %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %} Посты авторов по подписке {% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/publications.html' with pub_group=True %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества {{ group.title }} {% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    {% include 'includes/publications.html' with pub_group=False %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/publications.html' with pub_group=True %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {{ post|truncatechars:30 }} {% endblock %}
{% block content %}
  {% include 'includes/detail_publications.html'%}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
  {% if user != author %}
    {% include 'includes/profile_header.html'%}
  {% endif %}
  {% for post in page_obj %}
    {% include 'includes/profile_publications.html'%}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}